---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-external-secret
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: secret-to-be-created
    creationPolicy: Owner
  data:
    - secretKey: somepassword
      remoteRef:
        key: /tenants/tenant1/secrets/default
        property: test-secret