globalArguments:
- --serverstransport.insecureskipverify=true

ports:
  traefik:
    port: 9000
    expose:
      default: false
    exposedPort: 9000
    protocol: TCP
  web:
    port: 8000
    expose:
      default: true
    exposedPort: 80
    hostPort: 80
    protocol: TCP
    transport:
      respondingTimeouts:
        readTimeout:
        writeTimeout:
        idleTimeout:
      lifeCycle:
        requestAcceptGraceTimeout:
        graceTimeOut:
      keepAliveMaxRequests:
      keepAliveMaxTime:
  websecure:
    port: 8443
    hostPort: 443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP
    http3:
      enabled: false
    transport:
      respondingTimeouts:
        readTimeout:
        writeTimeout:
        idleTimeout:
      lifeCycle:
        requestAcceptGraceTimeout:
        graceTimeOut:
      keepAliveMaxRequests:
      keepAliveMaxTime:
    tls:
      enabled: true
      options: ""
      certResolver: ""
      domains: []
    middlewares: []
  metrics:
    port: 9100
    expose:
      default: false
    exposedPort: 9100
    protocol: TCP